name: 'GitHub Actions WakaTime robot'

on:
  push:
  schedule:
    - cron: '0 1 * * * '

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@master
      - name: 'Install jq comand'
        run: sudo apt-get install jq
      - name: 'Run shell'
        env:
          waka_user_id: ${{ secrets.WAKA_USER_ID }}
          waka_access_token: ${{ secrets.WAKA_ACCESS_TOKEN }}
          feishu_bot_token: ${{ secrets.FEISHU_BOT_TOKEN }}
        run: bash ./wakatime-robot.sh "$waka_user_id" "$waka_access_token" "$feishu_bot_token"